import type { Metadata } from "next";
import SiteHeader from "@/components/ContactComponents/SiteHeader/SiteHeader";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Aider Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
